# Generated by Django 4.2.5 on 2023-09-19 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('municipal', '0003_alter_municipalprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipalprofile',
            name='is_municipal_user',
        ),
    ]
