# Generated by Django 4.2.5 on 2023-09-21 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('municipal', '0004_remove_municipalprofile_is_municipal_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('description', models.TextField()),
                ('municipal_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='municipal.municipalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DataReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('water_consumption', models.DecimalField(decimal_places=2, max_digits=10)),
                ('electricity_consumption', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='municipal.location')),
            ],
        ),
    ]
