# Generated by Django 4.2.5 on 2023-09-19 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industrial', '0003_alter_industrialprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industrialprofile',
            name='is_industrial_user',
        ),
    ]
