# Generated by Django 4.2.5 on 2023-09-19 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('households', '0002_householdsprofile_is_household_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='householdsprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='household_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
