# Generated by Django 4.2.5 on 2023-09-19 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0004_remove_householdsprofile_is_household_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdWaterConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='households.householdsprofile')),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdElectricityConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='households.householdsprofile')),
            ],
        ),
    ]
