# Generated by Django 4.2.5 on 2023-09-22 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0006_alter_householdelectricityconsumption_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumptionGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('electricity_goal', models.FloatField()),
                ('water_goal', models.FloatField()),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='households.householdsprofile')),
            ],
        ),
    ]
